### ISSUE TITLE
cannot read property getCurrentMode of undefind at object.r.onModified

### ISSUE THREAD

**Issue by wu0211** [duty-os/white-react-demo#30]
![image](https://user-images.githubusercontent.com/34398833/82276670-7ab5fa00-99b8-11ea-94ab-c3a6da72b398.png)

在windows 系统中运行出现的问题

cannot read property getCurrentMode of undefind at object.r.onModified

**Comment by leavesster** [comment]
有可能是在 vue 中，使用 this.room = room 导致的。sdk 产生的 room 对象，并不是一个简单的 key-value object，与 vue 的监听不兼容。
如需绑定，请使用 this.$room = room 等行为。该行为为 VUE 官方推荐。
